blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/ivan-saorin/python-remote-mcp-with-app-template/discussions
    about: Please ask and answer questions here
  - name: MCP Documentation
    url: https://modelcontextprotocol.io/docs
    about: Check the official MCP documentation
